### ISSUE TITLE
Summit UI - Migration Plan Retry not working

### ISSUE THREAD

**Issue by bthurber** [ManageIQ/miq_v2v_ui_plugin#271]
If a migration plan failed, clicking Retry doesn't retry the migration.  Nothing happens.

**Comment by michaelkro** [comment]
This was actually resolved in https://github.com/priley86/miq_v2v_ui_plugin/pull/229, but this PR was merged into `sprint6`, and was not merged in `sprint7` nor `alpha`

**Comment by AparnaKarve** [comment]
Thanks @michaelkro -- I will look into cherry-picking the #229 commits to `alpha`

**Comment by priley86** [comment]
thanks @michaelkro - it looks like this is the only regression missed from sprint6? 
https://github.com/priley86/miq_v2v_ui_plugin/compare/alpha...sprint6?expand=1

the "fix browser tab title and icon" was pulled in by https://github.com/priley86/miq_v2v_ui_plugin/commit/767467e2b2a71cddaf28fa9d6523993a4866ee6d already it seems...

**Comment by kedark3** [comment]
@bthurber @priley86 Retry button does restart the migration, just does not show in the UI.

**Comment by kedark3** [comment]
With PR #296, I can see Retry operation shows Item being retried in the "In progress" section. 
But, It still have some issues. I ran a migration with 3 VMs, 1 migrated and 2 Failed. When I hit retry, the entry from Completed Migrations list disappeared, and it appeared in the "In Progress" section briefly, then failed and appeared in "Completed Migrations" section again. So far it sounds good. But problems are as follows:
1) I expect that when I retry, a new entry of "Retried" job appears in "Migrations completed" instead of updating previous entry. Maybe with a name format as "PlanName_Retry"
2) When I saw the newly updated entry, it said 1 of 3 VMs migrated, in "Migration Completed" list/section. But when I drilled down to details, it showed only 2 VMs, instead of 3.

**Comment by kedark3** [comment]
@AparnaKarve yes you got the first point correct. I would like to preserve records of every run/retry and make it accessible. Its better to keep track and see logs and other statistics for each of those independently. 
To see the second error, please use my appliance from yesterday, ending in .229 and check plan7.

**Comment by AparnaKarve** [comment]
@kedark3 Thanks.

We do preserve records of every run/retry as a "Request with associated Tasks" record.
In the UI however, we only show the most recent request data (and not the previous requests, which could be the failed requests)

Your above suggestion will need a change in the current UX design -- maybe an additional view to browse through old requests of a Plan.

**Comment by kedark3** [comment]
@AparnaKarve thanks for looking into it. I will still be rooting for the option where we have separate records for each for better transparency. @bthurber looking for your thoughts.

**Comment by bthurber** [comment]
Agree with @priley86

**Comment by kedark3** [comment]
Thanks for your input guys.

**Comment by bzwei** [comment]
@AparnaKarve It is by design that retry job only picks failed tasks. UI needs to aggregate all tasks from retry jobs. It is not appropriate to copy completed tasks into a retry job.

**Comment by priley86** [comment]
@AparnaKarve should this issue be renamed to "Show completed VMs for previous executions on the detail screen"? Would be nice to get this one in soon...

**Comment by AparnaKarve** [comment]
@priley86 The discussion here has transformed from -
`Migration Plan Retry not working`
to
`Show completed VMs for previous executions on the detail screen` :)

So maybe we can close this issue which was originally about "Retry"
and open a new issue with the title you suggested.

**Comment by AparnaKarve** [comment]
@priley86 Also, we will need UX details for how to - `Show completed VMs for previous executions on the detail screen`

**Comment by vconzola** [comment]
@priley86 @AparnaKarve This one's been sitting idle for a while... I assumed all along that completed VMs from previous executions were being shown on the details page of subsequent executions, but I guess it was never explicitly stated. I also assumed that the log information would just be appended to to previous requests when a secondary request is executed. If it doesn't work that way, we can discuss other ideas. However, I remain strongly against KKs idea of having "versions" of a plan. I think that will lead to alot of confusion.

**Comment by serenamarie125** [comment]
Closing this issue because retry now works.  Tracking the details of previously migrated VMs in https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/374
